// AUTO-GENERATED by scripts/generate-vocab-edge.mjs
// Source of truth: src/lib/textileVocabulary.js
// DO NOT EDIT BY HAND — re-run the codegen script and commit.

export const CATEGORIES = ["part","fabric_type","fibre","accessory","trim","size","direction","treatment","colour","label_type","polybag_type","sticker_type","zipper_type","stiffener_type","insert_card_type","carton_type","trim_detail_type"] as const;
export const PRODUCT_FAMILIES = ["Pillow Protector","Mattress Protector","Sleeper Encasement","Total Encasement","Sheet Set","Pillow Case","Comforter","Duvet Cover","Mattress Topper","Bed Skirt","Throw"] as const;

// ── part ────────────────────────────────────────────────
export const PART_CANONICALS = ["Back","Binding","Bottom","Evalon Membrane","Fabric Bag","Filling","Fitted Sheet","Flat Sheet","Front","Inner","Lamination","Outer","Pillow Case","Pillow Compression","Piping","Platform","Quilting","Sham","Skirt","Sleeper Flap","Top Fabric","Window"] as const;
export const PART_ALIASES = ["back panel","border","bottom fabric","bottom panel","deep pocket fitted sheet","drawstring bag","evalon","fill","fitted sheet and split top fitted sheet","fittedsheet","flap","flatsheet","front panel","inner fabric","inner liner","laminate","outer fabric","outer shell","pillow case 1pc","pillow case 2pc","pillow cases","pillow sham","pillowcase","quilt","self fabric bag","self-fabric bag","shams","side panel","split head fitted sheet","split top fitted sheet","stuffing","top","top panel","top sheet","top-sheet","window inside","window outside"] as const;

// ── fabric_type ────────────────────────────────────────────────
export const FABRIC_TYPE_CANONICALS = ["Damask","Flannel","French Terry","Interlock Knit","Jacquard","Jersey Knit","Microfiber","Non-woven","PU Laminate","Percale","Pique Knit","Plain Weave","Poplin","Rib Knit","Sateen","TPU Laminate","Tricot Knit","Twill","Velour"] as const;
export const FABRIC_TYPE_ALIASES = ["broadcloth","double knit","flannelette","interlock","jersey","knit jersey","micro-fiber","microfibre","non woven","nonwoven","percale weave","pique","polyurethane laminate","pu","rib","ribbed","sateen weave","single jersey","spunbond","terry","thermoplastic polyurethane","tpu","tpu film","tricot","twill weave","velour knit"] as const;

// ── fibre ────────────────────────────────────────────────
export const FIBRE_CANONICALS = ["Acrylic","Bamboo","Cotton","Egyptian Cotton","Linen","Lyocell","Microfiber Polyester","Modal","Nylon","Pima Cotton","Polyester","Rayon","Silk","Spandex","Supima Cotton","Wool"] as const;
export const FIBRE_ALIASES = ["bamboo rayon","bamboo viscose","cot","egypt cotton","elastane","flax","lycra","pa","pet","pima","poly","polyamide","polyester microfiber","supima","tencel","viscose"] as const;

// ── accessory ────────────────────────────────────────────────
export const ACCESSORY_CANONICALS = ["Brand Label","Button","Care Label","Drawcord","Elastic","Hang Tag","Insert Card","Label","Law Tag","PVC Bag","Packaging","Polybag","Size Label","Snap","Sticker","Stiffener","Tape","Thread","Velcro","Zipper"] as const;
export const ACCESSORY_ALIASES = ["barcode","barcode sticker","barcode sticker size","binding tape","ca law tag","card board","cardboard insert","cardboard stiffener","carton box","cord","decorative sticker","drawstring","elastic band","elastic tape","hanging tag","hangtag","hook and loop","informational insert","ldpe bag","main label","marketing card","master carton","matched thread","moisture pp bag","neck label","plastic bag","poly bag","pp bag","press stud","price tag","product label","ribbon tape","sewing insert label","sewing thread","size sticker","size tag","snap button","stiffener size","swing tag","u cardboard","vinyl bag","vinyl pvc bag","wash label","washing label","ykk zipper","zip","zip closure"] as const;

// ── trim ────────────────────────────────────────────────
export const TRIM_CANONICALS = ["Binding","Buckle","Button","Dori","Drawstring","Elastic","Eyelet","Hook & Eye","Interlining","Lace","Patch","Piping","Ribbon","Snap Button","Stitching Thread","Tape","Thread","Velcro","Zipper"] as const;
export const TRIM_ALIASES = ["binding tape","draw string","grommet","hook","hook and eye","hook and loop","matched thread","press stud","sewing thread","slider","snap","zip"] as const;

// ── size ────────────────────────────────────────────────
export const SIZE_CANONICALS = ["Body Pillow","Cal King","Full","Full XL","King","King Pillow","King/Cal King","Queen","Queen Pillow","Split Cal King","Split Head Cal King","Split Head King","Split Head Queen","Split King","Split Queen","Standard Pillow","Travel Pillow","Twin","Twin XL","Twin/Twin XL"] as const;
export const SIZE_ALIASES = ["body","california king","calking","ck","double","f","fullxl","fxl","k","k pillow","k/ck","kck","king cal king","q","q pillow","sck","shck","shk","shq","sk","spck","spk","split head ck","sq","standard","std pillow","t","travel","ttxl","twin twin xl","twinxl","tx","txl"] as const;

// ── direction ────────────────────────────────────────────────
export const DIRECTION_CANONICALS = ["Bias","LXL","LXW","WXL","WXW"] as const;
export const DIRECTION_ALIASES = ["45deg","diagonal","l x l","l x w","l*w","length x width","lengthwise","lengthwise both","w x l","w x w","w*l","warpwise","width x length","widthwise both"] as const;

// ── treatment ────────────────────────────────────────────────
export const TREATMENT_CANONICALS = ["Antimicrobial","Brushed","Cooling","Flame Retardant","Mercerised","Sanforised","Stain Repellent","Water Resistant","Waterproof","Wrinkle Free"] as const;
export const TREATMENT_ALIASES = ["anti-microbial","brushed finish","cool touch","dwr","fire retardant","fr","hydrophobic","mercerized","no-iron","pre-shrunk","sanforized","scotchgard","silvadur","stain release","stretch cool","water proof","water-proof","water-resistant","wrinkle-free"] as const;

// ── colour ────────────────────────────────────────────────
export const COLOUR_CANONICALS = ["Beige","Black","Blue","Brown","Cloud Gray","Dark Grey","Dove Gray","Green","Grey","Ivory","Light Blue","Light Grey","Misty Blue","Navy","Pink","Purple","Red","White","Yellow"] as const;
export const COLOUR_ALIASES = ["bg","bk","bl","blk","br","br-n","cg","charcoal","cloud grey","cream","dark gray","dove","dove grey","gn","gr","gray","gy","iv","lb","light gray","lt blue","lt gray","lt grey","mb","mist blue","natural","navy blue","nb","off-white","pk","pr","rd","silver","sky blue","tan","violet","wh","wt","yl"] as const;

// ── label_type ────────────────────────────────────────────────
export const LABEL_TYPE_CANONICALS = ["Barcode Label","Brand Label","Care Label","Care label in 3 Languages 1X3","Compliance Label","Composition Label","Country of Origin Label","Custom Label","Direction Label","Eco Label","GOTS Label","Hang Tag","Price Ticket","Retailer Label","Size Label","Wash Label"] as const;
export const LABEL_TYPE_ALIASES = ["1x3","3 language care label","barcode","brand","care instruction","care label 3-lang","ce mark","compliance","composition","content label","coo","country of origin","custom","direction","ean label","eco","fair trade","fiber content","fibre content","foot end","fsc","gots","hanging tag","hangtag","head end","iso 9001","laundry label","logo","logo label","made in","main label","msrp","neck label","oeko-tex","oekotex","organic label","origin label","price tag","private label","product label","retail price","size tag","store label","swing tag","swing ticket","this side up","ticket","top-bottom","tri-lingual care","upc label","wash care","wash instruction","washing label"] as const;

// ── polybag_type ────────────────────────────────────────────────
export const POLYBAG_TYPE_CANONICALS = ["LDPE","OPP","PE","PP","PVC"] as const;
export const POLYBAG_TYPE_ALIASES = ["biaxially-oriented polypropylene","low density polyethylene","moisture pp","oriented polypropylene","pe bag","polyethylene","polypropylene","pvc bag","vinyl"] as const;

// ── sticker_type ────────────────────────────────────────────────
export const STICKER_TYPE_CANONICALS = ["Barcode Sticker","Compliance Sticker","Custom Sticker","Packaging Info Sticker","QR Code Sticker","Retailer Sticker","Size Sticker","UPC Sticker","Warning Sticker"] as const;
export const STICKER_TYPE_ALIASES = ["barcode","caution sticker","custom","packaging info","qr","qr code","upc","warning label"] as const;

// ── zipper_type ────────────────────────────────────────────────
export const ZIPPER_TYPE_CANONICALS = ["Coil Zipper","Custom","Invisible Zipper","Metal Zipper","Plastic Molded Zipper","SBS Nylon Zipper"] as const;
export const ZIPPER_TYPE_ALIASES = ["coil","custom zipper","invisible","metal","molded plastic","nylon zipper","plastic molded","sbs nylon"] as const;

// ── stiffener_type ────────────────────────────────────────────────
export const STIFFENER_TYPE_CANONICALS = ["Bux Board","Cardboard","Corrugated","Foam Board","MDF","Other","PVC Sheet"] as const;
export const STIFFENER_TYPE_ALIASES = ["card board","card stiffener","custom","foam","pvc","u cardboard","u shape","u-shape"] as const;

// ── insert_card_type ────────────────────────────────────────────────
export const INSERT_CARD_TYPE_CANONICALS = ["Art Card","Bleach Card","Box Packaging","Bux Board","Custom"] as const;
export const INSERT_CARD_TYPE_ALIASES = ["box","color paper","color paper insert","marketing card"] as const;

// ── carton_type ────────────────────────────────────────────────
export const CARTON_TYPE_CANONICALS = ["Brown","Plain","Printed","White"] as const;
export const CARTON_TYPE_ALIASES = ["brown carton","kraft","kraft carton","plain carton","printed carton","white carton"] as const;

// ── trim_detail_type ────────────────────────────────────────────────
export const TRIM_DETAIL_TYPE_CANONICALS = ["Button","Cord Lock","Custom","Drawcord","Drawcord Stopper","Elastic","Jacquard Band","Piping","Ribbon","Rivet","Velcro"] as const;
export const TRIM_DETAIL_TYPE_ALIASES = ["cord","cord stopper","drawstring","elastic band","elastic tape","hook and loop","jacquard","stopper"] as const;

// Words that are NEVER valid component_type values — they belong in fabric_type.
export const FABRIC_FORBIDDEN_IN_COMPONENT_TYPE = ["acrylic","bamboo","bamboo rayon","bamboo viscose","broadcloth","cot","cotton","damask","double knit","egypt cotton","egyptian cotton","elastane","flannel","flannelette","flax","french terry","interlock","interlock knit","jacquard","jersey","jersey knit","knit jersey","linen","lycra","lyocell","micro-fiber","microfiber","microfiber polyester","microfibre","modal","non woven","non-woven","nonwoven","nylon","pa","percale","percale weave","pet","pima","pima cotton","pique","pique knit","plain weave","poly","polyamide","polyester","polyester microfiber","polyurethane laminate","poplin","pu","pu laminate","rayon","rib","rib knit","ribbed","sateen","sateen weave","silk","single jersey","spandex","spunbond","supima","supima cotton","tencel","terry","thermoplastic polyurethane","tpu","tpu film","tpu laminate","tricot","tricot knit","twill","twill weave","velour","velour knit","viscose","wool"] as const;

/** Case-insensitive membership check across canonicals + aliases for a category. */
export function isInCategory(
  category: keyof typeof _ALL_BY_CATEGORY,
  value: string,
): boolean {
  if (!value) return false;
  const v = value.toString().toLowerCase().trim().replace(/\s+/g, " ");
  if (!v) return false;
  const list = _ALL_BY_CATEGORY[category];
  return list?.has(v) ?? false;
}

const _ALL_BY_CATEGORY: Record<string, Set<string>> = {
  part: new Set(["back","back panel","binding","border","bottom","bottom fabric","bottom panel","deep pocket fitted sheet","drawstring bag","evalon","evalon membrane","fabric bag","fill","filling","fitted sheet","fitted sheet and split top fitted sheet","fittedsheet","flap","flat sheet","flatsheet","front","front panel","inner","inner fabric","inner liner","laminate","lamination","outer","outer fabric","outer shell","pillow case","pillow case 1pc","pillow case 2pc","pillow cases","pillow compression","pillow sham","pillowcase","piping","platform","quilt","quilting","self fabric bag","self-fabric bag","sham","shams","side panel","skirt","sleeper flap","split head fitted sheet","split top fitted sheet","stuffing","top","top fabric","top panel","top sheet","top-sheet","window","window inside","window outside"]),
  fabric_type: new Set(["broadcloth","damask","double knit","flannel","flannelette","french terry","interlock","interlock knit","jacquard","jersey","jersey knit","knit jersey","micro-fiber","microfiber","microfibre","non woven","non-woven","nonwoven","percale","percale weave","pique","pique knit","plain weave","polyurethane laminate","poplin","pu","pu laminate","rib","rib knit","ribbed","sateen","sateen weave","single jersey","spunbond","terry","thermoplastic polyurethane","tpu","tpu film","tpu laminate","tricot","tricot knit","twill","twill weave","velour","velour knit"]),
  fibre: new Set(["acrylic","bamboo","bamboo rayon","bamboo viscose","cot","cotton","egypt cotton","egyptian cotton","elastane","flax","linen","lycra","lyocell","microfiber polyester","modal","nylon","pa","pet","pima","pima cotton","poly","polyamide","polyester","polyester microfiber","rayon","silk","spandex","supima","supima cotton","tencel","viscose","wool"]),
  accessory: new Set(["barcode","barcode sticker","barcode sticker size","binding tape","brand label","button","ca law tag","card board","cardboard insert","cardboard stiffener","care label","carton box","cord","decorative sticker","drawcord","drawstring","elastic","elastic band","elastic tape","hang tag","hanging tag","hangtag","hook and loop","informational insert","insert card","label","law tag","ldpe bag","main label","marketing card","master carton","matched thread","moisture pp bag","neck label","packaging","plastic bag","poly bag","polybag","pp bag","press stud","price tag","product label","pvc bag","ribbon tape","sewing insert label","sewing thread","size label","size sticker","size tag","snap","snap button","sticker","stiffener","stiffener size","swing tag","tape","thread","u cardboard","velcro","vinyl bag","vinyl pvc bag","wash label","washing label","ykk zipper","zip","zip closure","zipper"]),
  trim: new Set(["binding","binding tape","buckle","button","dori","draw string","drawstring","elastic","eyelet","grommet","hook","hook & eye","hook and eye","hook and loop","interlining","lace","matched thread","patch","piping","press stud","ribbon","sewing thread","slider","snap","snap button","stitching thread","tape","thread","velcro","zip","zipper"]),
  size: new Set(["body","body pillow","cal king","california king","calking","ck","double","f","full","full xl","fullxl","fxl","k","k pillow","k/ck","kck","king","king cal king","king pillow","king/cal king","q","q pillow","queen","queen pillow","sck","shck","shk","shq","sk","spck","spk","split cal king","split head cal king","split head ck","split head king","split head queen","split king","split queen","sq","standard","standard pillow","std pillow","t","travel","travel pillow","ttxl","twin","twin twin xl","twin xl","twin/twin xl","twinxl","tx","txl"]),
  direction: new Set(["45deg","bias","diagonal","l x l","l x w","l*w","length x width","lengthwise","lengthwise both","lxl","lxw","w x l","w x w","w*l","warpwise","width x length","widthwise both","wxl","wxw"]),
  treatment: new Set(["anti-microbial","antimicrobial","brushed","brushed finish","cool touch","cooling","dwr","fire retardant","flame retardant","fr","hydrophobic","mercerised","mercerized","no-iron","pre-shrunk","sanforised","sanforized","scotchgard","silvadur","stain release","stain repellent","stretch cool","water proof","water resistant","water-proof","water-resistant","waterproof","wrinkle free","wrinkle-free"]),
  colour: new Set(["beige","bg","bk","bl","black","blk","blue","br","br-n","brown","cg","charcoal","cloud gray","cloud grey","cream","dark gray","dark grey","dove","dove gray","dove grey","gn","gr","gray","green","grey","gy","iv","ivory","lb","light blue","light gray","light grey","lt blue","lt gray","lt grey","mb","mist blue","misty blue","natural","navy","navy blue","nb","off-white","pink","pk","pr","purple","rd","red","silver","sky blue","tan","violet","wh","white","wt","yellow","yl"]),
  label_type: new Set(["1x3","3 language care label","barcode","barcode label","brand","brand label","care instruction","care label","care label 3-lang","care label in 3 languages 1x3","ce mark","compliance","compliance label","composition","composition label","content label","coo","country of origin","country of origin label","custom","custom label","direction","direction label","ean label","eco","eco label","fair trade","fiber content","fibre content","foot end","fsc","gots","gots label","hang tag","hanging tag","hangtag","head end","iso 9001","laundry label","logo","logo label","made in","main label","msrp","neck label","oeko-tex","oekotex","organic label","origin label","price tag","price ticket","private label","product label","retail price","retailer label","size label","size tag","store label","swing tag","swing ticket","this side up","ticket","top-bottom","tri-lingual care","upc label","wash care","wash instruction","wash label","washing label"]),
  polybag_type: new Set(["biaxially-oriented polypropylene","ldpe","low density polyethylene","moisture pp","opp","oriented polypropylene","pe","pe bag","polyethylene","polypropylene","pp","pvc","pvc bag","vinyl"]),
  sticker_type: new Set(["barcode","barcode sticker","caution sticker","compliance sticker","custom","custom sticker","packaging info","packaging info sticker","qr","qr code","qr code sticker","retailer sticker","size sticker","upc","upc sticker","warning label","warning sticker"]),
  zipper_type: new Set(["coil","coil zipper","custom","custom zipper","invisible","invisible zipper","metal","metal zipper","molded plastic","nylon zipper","plastic molded","plastic molded zipper","sbs nylon","sbs nylon zipper"]),
  stiffener_type: new Set(["bux board","card board","card stiffener","cardboard","corrugated","custom","foam","foam board","mdf","other","pvc","pvc sheet","u cardboard","u shape","u-shape"]),
  insert_card_type: new Set(["art card","bleach card","box","box packaging","bux board","color paper","color paper insert","custom","marketing card"]),
  carton_type: new Set(["brown","brown carton","kraft","kraft carton","plain","plain carton","printed","printed carton","white","white carton"]),
  trim_detail_type: new Set(["button","cord","cord lock","cord stopper","custom","drawcord","drawcord stopper","drawstring","elastic","elastic band","elastic tape","hook and loop","jacquard","jacquard band","piping","ribbon","rivet","stopper","velcro"]),
};
